### ISSUE TITLE
Any plans to release code?

### ISSUE THREAD

**Issue by ChidanandKumarKS** [VicenteAlex/Spiking_ResNet#1]
Any plans to release code?

**Comment by VicenteAlex** [comment]
Hello. We decided to release the code after the paper is accepted for publication. The earliest this could be is in January. 

Thank you for your interest

**Comment by ChidanandKumarKS** [comment]
@VicenteAlex 
Do you have any updates?

**Comment by VicenteAlex** [comment]
The paper is still under review, it looks like the earliest it could be accepted is end of April or May.

**Comment by mountains-high** [comment]
Good day, Mr. @VicenteAlex,

Is it possible to release the code now? Thank you for your considerations 
Will be available some trained models for CIFAR-10? Thanks

**Comment by zhangyu199802** [comment]
@VicenteAlex hello，could you please release the code now?

**Comment by VicenteAlex** [comment]
The code is now available.
@mountains-high I will be making the pre-trained models available as soon as possible.

Thank you all for your interest

**Comment by mountains-high** [comment]
> The code is now available. @mountains-high I will be making the pre-trained models available as soon as possible.
> 
> Thank you all for your interest

Good day,

Thank you for your consideration. I will be grateful if you could share pre-trained weights on CIFAR-10.

Thank you~

**Comment by VicenteAlex** [comment]
The pre-trained weights can be accessed through the link in the readme "Pre-trained models can be downloaded here".

I have uploaded the best performing configurations, but if other configurations from the ones defined in the paper are of interest I can also upload them.

If that is not working or not clear, please let me know.

Thank you

**Comment by mountains-high** [comment]
> I have uploaded the best performing configurations, but if other configurations from the ones defined in the paper are of interest I can also upload them.

Dear Vicente Alex, 

Could you upload other configurations that perform best? Particularly, obtaining Table 3. & all models trained on CIFAR-10 datasets. 

Thank you very much ~
